#!/usr/bin/env bash
set -e # Exit immediately if a command fails

VENV=".venv"
minilibx_DIR="external/minilibx"
minilibx_TGZ="${minilibx_DIR}/mlx_CLXV-2.2.tgz"
minilibx_CPP_DIR="${minilibx_DIR}/mlx_CLXV"
# minilibx_WHEEL="./external/minilibx/mlx-2.2-py3-ubuntu-any.whl"

# 1. Environment Creation
if [ ! -d "$VENV" ]; then
    echo "==> Creating virtual environment..."
    python3 -m venv "$VENV"
fi

# 2. Upgrade pip
echo "==> Upgrading pip..."
"$VENV/bin/pip" install --upgrade pip

# Unpack
if [ ! -d "$minilibx_CPP_DIR" ]; then
    tar -xzf "$minilibx_TGZ" -C external/minilibx/
fi

# Compile C++
make -C "$minilibx_CPP_DIR"

# Find the actual wheel generated by the Makefile
minilibx_WHEEL=$(ls $minilibx_DIR/mlx-*.whl | head -n 1)

if [ -z "$minilibx_WHEEL" ]; then
    echo "❌ ERROR: No .whl file found after compilation."
    exit 1
fi

# Define the generic name
GENERIC_minilibx_WHEEL="$minilibx_DIR/mlx-2.2-py3-none-any.whl"

# Rename only if it's not already named correctly
if [ "$minilibx_WHEEL" != "$GENERIC_minilibx_WHEEL" ]; then
    echo "🏷️  Renaming $(basename "$minilibx_WHEEL") to $(basename "$GENERIC_minilibx_WHEEL")"
    mv "$minilibx_WHEEL" "$GENERIC_minilibx_WHEEL"
fi

# # 4. Install the renamed wheel
# echo "🐍 Installing Python wrapper..."
# pip install "$GENERIC_minilibx_WHEEL" --force-reinstall

# 3. Local Wheel Handshake
if [ -f "$GENERIC_minilibx_WHEEL" ]; then
    echo "==>🐍 Installing Python minilibx wrapper..."
    "$VENV/bin/pip" install "$GENERIC_minilibx_WHEEL" --force-reinstall
else
    echo "ERROR: $GENERIC_minilibx_WHEEL not found. Check the /external folder."
    exit 1
fi
#[ -L "$(python3 -c 'import mlx; print(mlx.__path__[0])')/libmlx.so" ] && echo "✅ Symlink Created" || echo "❌ Link Failed"
#[ -e "$(python3 -c 'import mlx; print(mlx.__path__[0])')/libmlx.so" ] && echo "✅ Target Found" || echo "❌ Target Missing (Dangling Link)"
# test -e "$(python3 -c 'import mlx; print(mlx.__path__[0])')/libmlx.so" || { echo "❌ ERROR: Symbolic link is dangling or destination missing."; exit 1; }
minilibx_VENVPATH=$(python3 -c "import mlx; print(mlx.__path__[0])")
ln -sf "${minilibx_CPP_DIR}/libmlx.so" "$minilibx_VENVPATH/libmlx.so"
SO_TARGET="$minilibx_VENVPATH/libmlx.so"
if [ -e "$SO_TARGET" ]; then
    echo "✅ MLX Handshake: Success. Link is valid at $SO_TARGET"
else
    echo "❌ MLX Handshake: ERROR. The symbolic link is broken or the source binary is missing."
    exit 1
fi

echo "🧪 Running Final Integration Test..."

# We capture the output and check for the specific '✅' success message
if python3 -c "import mlx; m = mlx.Mlx(); print('✅ Library Connection Proven: ' + m.so_file)" 2>&1 | grep -q "✅"; then
    echo "🏁 MiniLibX is fully operational."
else
    echo "❌ ERROR: Python found the module but could not initialize the C++ library."
    exit 1
fi

# 4. Project Setup
echo "==> Installing project in editable mode..."
"$VENV/bin/pip" install -e .

# Detection for the user's current shell
CURRENT_SHELL=$(basename "$SHELL")
echo "==> Setup Complete!"
echo "==> To activate, run: source $VENV/bin/activate"